apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: apiserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  strategy: {}
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: jkplayground/smartbank-api-module:v1.0.0
          name: sba-apiserver
          resources: {}
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres:5432/app
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: spring.application.name
              value: sba-apiserver
          volumeMounts:
            - name: secret-vol
              mountPath: "/etc/app"
              readOnly: true
          initContainers:
            # ensure installation of elastic agent before apiserver startup
            - name: postgres
      volumes:
        - name: secret-vol
          secret:
            secretName: db

status: {}
