apiVersion: v1
kind: Service
metadata:
  labels:
    app: dynamodb
  name: dynamodb
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: dynamodb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamodb
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  strategy: {}
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: hub.brainupgrade.net/junkin/sba-dynamodb:3
          name: sba-dynamodb
          resources: {}
          env:
            - name: spring.application.name
              value: sba-dynamodb
            # usage ENV var
            - name: cloud.aws.region.static
              valueFrom:
                secretKeyRef:
                  name: usage
                  key: cloud_aws_region_static
            - name: cloud.aws.credentials.access-key
              valueFrom:
                secretKeyRef:
                  name: usage
                  key: cloud_aws_credentials_access_key
            - name: cloud.aws.credentials.secret-key
              valueFrom:
                secretKeyRef:
                  name: usage
                  key: cloud_aws_credentials_secret_key
            - name: cloud.aws.end-point.uri-usage
              valueFrom:
                secretKeyRef:
                  name: usage
                  key: cloud_aws_endpoint_uri_usage
          volumeMounts:
            - name: usage-secret-vol
              mountPath: "/etc/app"
              readOnly: true
      volumes:
        - name: usage-secret-vol
          secret:
            secretName: usage
status: {}
